@php
/**
 * Partial: body del reporte de tamizaje.
 * Variables del padre: $psychologist, $patient, $request, $items, $generatedAt
 * Variable propia: $lang ('en' | 'es')
 */
$t = ($lang === 'en') ? [
    'report_subtitle' => 'Psychological Screening Report',
    'license'         => 'License',
    'patient_section' => 'Patient Information',
    'full_name'       => 'Full name',
    'sex'             => 'Sex',
    'dob'             => 'Date of birth',
    'age'             => 'Age',
    'age_unit'        => 'years',
    'sex_labels'      => [
        'male'              => 'Male',
        'female'            => 'Female',
        'other'             => 'Other',
        'prefer_not_to_say' => 'Prefer not to say',
    ],
    'eval_section'     => 'Assessment Information',
    'applied_date'     => 'Application date',
    'report_date'      => 'Report date',
    'tests_applied'    => 'Test(s) applied',
    'total_score'      => 'Total score',
    'severity_labels'  => [
        'Mínima'   => 'Minimal',
        'Leve'     => 'Mild',
        'Moderada' => 'Moderate',
        'Severa'   => 'Severe',
    ],
    'chart_title'      => 'Item response profile',
    'col_item'         => 'Item',
    'col_answer'       => 'Selected response',
    'col_score'        => 'Score',
    'scale_version'    => 'Scale version',
    'disclaimer_title' => 'IMPORTANT NOTICE',
    'disclaimer_text'  => config('screening.pdf_disclaimer'),
    'generated_by'     => 'Generated by',
    'report_id'        => 'Report ID',
] : [
    'report_subtitle' => 'Reporte de Tamizaje Psicológico',
    'license'         => 'Cédula',
    'patient_section' => 'Datos del Paciente',
    'full_name'       => 'Nombre completo',
    'sex'             => 'Sexo',
    'dob'             => 'Fecha de nacimiento',
    'age'             => 'Edad',
    'age_unit'        => 'años',
    'sex_labels'      => [
        'male'              => 'Masculino',
        'female'            => 'Femenino',
        'other'             => 'Otro',
        'prefer_not_to_say' => 'Prefiero no decir',
    ],
    'eval_section'     => 'Información de la Evaluación',
    'applied_date'     => 'Fecha de aplicación',
    'report_date'      => 'Fecha del reporte',
    'tests_applied'    => 'Prueba(s) aplicada(s)',
    'total_score'      => 'Puntaje total',
    'severity_labels'  => [
        'Mínima'   => 'Mínima',
        'Leve'     => 'Leve',
        'Moderada' => 'Moderada',
        'Severa'   => 'Severa',
    ],
    'chart_title'      => 'Perfil de respuestas por ítem',
    'col_item'         => 'Ítem',
    'col_answer'       => 'Respuesta seleccionada',
    'col_score'        => 'Puntaje',
    'scale_version'    => 'Versión de la escala',
    'disclaimer_title' => 'AVISO IMPORTANTE',
    'disclaimer_text'  => 'Los resultados de esta herramienta de tamizaje no constituyen un diagnóstico por sí solos. Este reporte está destinado exclusivamente al uso de profesionales de salud mental calificados. Los resultados deben interpretarse en el contexto de una evaluación clínica integral.',
    'generated_by'     => 'Generado por',
    'report_id'        => 'Reporte ID',
];
@endphp

{{-- ENCABEZADO --}}
<div class="header">
    <div>
        @php $logoPath = public_path('logo.png'); @endphp
        @if(file_exists($logoPath))
            <img src="{{ $logoPath }}" style="height:50px; max-width:200px;" alt="{{ config('app.name') }}">
        @else
            <div style="font-size:20px;font-weight:bold;color:#5a7123;">{{ config('app.name') }}</div>
        @endif
        <div style="font-size:10px;color:#777;margin-top:4px;">{{ $t['report_subtitle'] }}</div>
    </div>
    <div class="psychologist-block">
        <strong>{{ $psychologist->name }}</strong><br>
        @if($psychologist->profile?->professional_license)
            {{ $t['license'] }}: {{ $psychologist->profile->professional_license }}<br>
        @endif
        @if($psychologist->profile?->specialty)
            {{ $psychologist->profile->specialty }}<br>
        @endif
        {{ $psychologist->email }}
    </div>
</div>

{{-- DATOS DEL PACIENTE --}}
<div class="section-title">{{ $t['patient_section'] }}</div>
<table>
    <tr>
        <th style="width:25%">{{ $t['full_name'] }}</th>
        <td>{{ $patient->full_name }}</td>
        <th style="width:15%">{{ $t['sex'] }}</th>
        <td>{{ $t['sex_labels'][$patient->sex] ?? '—' }}</td>
    </tr>
    <tr>
        <th>{{ $t['dob'] }}</th>
        <td>{{ $patient->date_of_birth?->format('d/m/Y') ?? '—' }}</td>
        <th>{{ $t['age'] }}</th>
        <td>{{ $patient->age ? $patient->age . ' ' . $t['age_unit'] : '—' }}</td>
    </tr>
</table>

{{-- INFO DE LA EVALUACIÓN --}}
<div class="section-title">{{ $t['eval_section'] }}</div>
<table>
    <tr>
        <th style="width:30%">{{ $t['applied_date'] }}</th>
        <td>{{ $request->completed_at?->setTimezone('America/Mexico_City')->format('d/m/Y H:i') ?? '—' }}</td>
        <th style="width:20%">{{ $t['report_date'] }}</th>
        <td>{{ $generatedAt->setTimezone('America/Mexico_City')->format('d/m/Y H:i') }}</td>
    </tr>
    <tr>
        <th>{{ $t['tests_applied'] }}</th>
        <td colspan="3">
            {{ $items->map(fn($i) => $i->assessment->name)->implode(', ') }}
        </td>
    </tr>
</table>

{{-- RESULTADOS POR PRUEBA --}}
@foreach($items as $item)
    @if($item->response)
        @php
            $response = $item->response;
            $colorMap = [
                'Mínima'   => ['#27ae60', '#e9f7ef'],
                'Leve'     => ['#f39c12', '#fef9e7'],
                'Moderada' => ['#e67e22', '#fdf2e9'],
                'Severa'   => ['#c0392b', '#fdedec'],
            ];
            $colors  = $colorMap[$response->severity_label] ?? ['#555', '#f0f0f0'];
            $answers = $response->answers->sortBy(fn($a) => $a->question->order)->values();
            $n       = $answers->count();
            $yMax    = max($answers->map(fn($a) => (int) $a->score_value_snapshot)->max() ?: 1, 1);
            $chartH  = 70;
            $severityDisplay = $t['severity_labels'][$response->severity_label] ?? $response->severity_label;
        @endphp

        <div class="section-title">
            {{ $item->assessment->name }}
            @if($item->assessment->short_name)
                ({{ $item->assessment->short_name }})
            @endif
        </div>

        {{-- Puntaje --}}
        <div class="score-box" style="border-color:{{ $colors[0] }};background:{{ $colors[1] }};">
            <div style="font-size:11px;color:#555;">{{ $t['total_score'] }}</div>
            <div class="score-label" style="color:{{ $colors[0] }};">
                {{ $response->total_score }}
                &nbsp;—&nbsp;
                <span class="badge" style="background:{{ $colors[0] }};color:white;">
                    {{ $severityDisplay }}
                </span>
            </div>
            <div class="interpretation">{{ $response->interpretation_text }}</div>
        </div>

        {{-- Gráfica de respuestas --}}
        @if($n > 0)
        <div class="chart-wrap">
            <div class="chart-title">{{ $t['chart_title'] }}</div>
            <table style="width:100%;border-collapse:collapse;table-layout:fixed;">
                {{-- Fila: valores encima de cada barra --}}
                <tr>
                    @foreach($answers as $answer)
                    @php
                        $score   = (int) $answer->score_value_snapshot;
                        $pct     = $yMax > 0 ? $score / $yMax : 0;
                        $itemClr = $pct == 0 ? '#27ae60' : ($pct <= 0.33 ? '#f39c12' : ($pct <= 0.66 ? '#e67e22' : '#c0392b'));
                    @endphp
                    <td style="text-align:center;padding:0;border:none;font-size:7px;font-weight:bold;color:{{ $itemClr }};vertical-align:bottom;height:12px;">
                        {{ $score > 0 ? $score : '' }}
                    </td>
                    @endforeach
                </tr>
                {{-- Fila: barras --}}
                <tr>
                    @foreach($answers as $answer)
                    @php
                        $score   = (int) $answer->score_value_snapshot;
                        $barH    = $yMax > 0 ? (int) round($score / $yMax * $chartH) : 0;
                        $pct     = $yMax > 0 ? $score / $yMax : 0;
                        $itemClr = $pct == 0 ? '#27ae60' : ($pct <= 0.33 ? '#f39c12' : ($pct <= 0.66 ? '#e67e22' : '#c0392b'));
                    @endphp
                    <td style="vertical-align:bottom;text-align:center;padding:0 2px;border:none;border-bottom:2px solid #aaa;height:{{ $chartH }}px;">
                        @if($barH > 0)
                        <div style="width:60%;margin:0 auto;height:{{ $barH }}px;background:{{ $itemClr }};border-radius:2px 2px 0 0;"></div>
                        @endif
                    </td>
                    @endforeach
                </tr>
                {{-- Fila: etiquetas eje X --}}
                <tr>
                    @foreach($answers as $i => $answer)
                    @php
                        $qLabel = $answer->question->question_code
                            ? $answer->question->question_code
                            : ('Q' . ($i + 1));
                    @endphp
                    <td style="text-align:center;padding:2px 0 0;border:none;font-size:7px;color:#555;">{{ $qLabel }}</td>
                    @endforeach
                </tr>
            </table>
        </div>
        @endif

        {{-- Respuestas individuales --}}
        <table>
            <thead>
                <tr>
                    <th>{{ $t['col_item'] }}</th>
                    <th style="width:35%">{{ $t['col_answer'] }}</th>
                    <th style="width:10%;text-align:center">{{ $t['col_score'] }}</th>
                </tr>
            </thead>
            <tbody>
                @foreach($answers as $answer)
                <tr class="answer-row">
                    <td>{{ $answer->question->question_text }}</td>
                    <td>{{ $answer->option_text_snapshot }}</td>
                    <td style="text-align:center">{{ $answer->score_value_snapshot }}</td>
                </tr>
                @endforeach
            </tbody>
        </table>

        <p style="font-size:9px;color:#777;margin-bottom:8px;">
            {{ $t['scale_version'] }}: {{ $response->assessment_version_snapshot ?? 'N/A' }}
        </p>
    @endif
@endforeach

{{-- DISCLAIMER --}}
<div class="disclaimer">
    <strong>{{ $t['disclaimer_title'] }}:</strong>
    {{ $t['disclaimer_text'] }}
</div>

{{-- PIE DE PÁGINA --}}
<div class="footer">
    {{ $t['generated_by'] }} {{ config('app.name') }} · {{ $generatedAt->format('d/m/Y H:i') }} ·
    {{ $t['report_id'] }}: {{ $request->id }}
</div>
